# Generated by Django 2.1 on 2020-09-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgage',
            new_name='image',
        ),
    ]
